import { LightningElement, track, api, wire } from "lwc";
import { ShowToastEvent } from "lightning/platformShowToastEvent";
import FirstName from '@salesforce/schema/Contact.FirstName';
//Imports for hide headers
import noHeader from '@salesforce/resourceUrl/NoHeader';
import HideLightningHeader from '@salesforce/resourceUrl/NoHeader';
import { loadStyle, loadScript } from 'lightning/platformResourceLoader';
import getemaildatafunction from '@salesforce/apex/Mailget.getemaildatafunction';
import sendingemail from '@salesforce/apex/Sendemail.sendingemail';
import Field from "@salesforce/schema/AccountHistory.Field";
import { NavigationMixin } from 'lightning/navigation';

export default class Signauth extends NavigationMixin(LightningElement)  {
  @track timecurrent
  @track emaillist = []
  @track dataer = {FirstName: "", LastName: ""};
  //User entered email address
  @track email = "";
  @track countdownDisplay = "";
  @track resendotpbtnvisibility = false;
  @track hideemailfield = false;
  //fomated otp generated variable
  @track otpdata;
  @track buttondisable = false;
  //user entered otp variable
  @track userenteredotp;
  @track buttonlabel = "Get OTP";
  @track firstbutton = true;
  @track secondbuttonlabel = "Submit";
  @track timeminutes;
  @track timestam = [];
  //togetlistofemailsfromapex
@track emaildata = [];
@track showotpfield = false;


//WIRE METHOD TO GET DATA FROM APEX
// @wire(getemaildatafunction,{usernameemail: "$email"})

// datafetchfromapex({data,error}){

//   if(data){
//       this.emaildata = data;
//   }else if(error)
//   window.alert("Fetch Error");
// }
 

navigatetohome(e) {
  this[NavigationMixin.Navigate]({
      "type": "standard__navItemPage",
      "attributes": {
          "apiName": "homepage"
      }
  });
}
  //GET USER INPUT DATA
 


    runfunc(event) {
        let getname = event.target.name;
      

        if(getname === "emailid"){
            this.email = event.target.value;
            this.dataer.FirstName = event.target.value;
        }else if(getname === "name"){
            this.userenteredotp = event.target.value;
            this.dataer.LastName = event.target.value;
        }
        // const event = new ShowToastEvent({
        //     title: "Success",  // Provide a valid title
        //     message: "Button clicked!",  // Provide a valid message
        //     variant: "success"
        //      // Ensure variant is correctly written
        // });

        // this.buttonlabel = "Submitted";
        // this.buttonlabel = "Submit";
        // this.dispatchEvent(event);
    }
    
    //USER VALIDATION FUNCTION
     validate(getemail){

      
      //  var lowercaseemail = this.emaildata.map((item =>{return item.toLowerCase()}))

      // if(lowercaseemail.includes(getemail)){
      //   window.alert("email found");
      // }else{
      //   window.alert("not found");
      // }

    }

    
    //BUTTON CLICK FUNCTION

     async btnclick (){

      //actual filtered email generated by users given email
     let getdatafromuser = this.email.toLowerCase();
      if(getdatafromuser.trim() === ""){
        window.alert("Please enter a valid email");
        return;
      }
      if(!getdatafromuser.endsWith("@gmail.com")){
          window.alert("authonticate error");
          return;
        }
      try{
        const result = await getemaildatafunction({usernameemail: getdatafromuser});

        if(!result || result.length === 0){
          window.alert("email not found");
          return;
        }
        let lowerresult = result.map(item => item.Email.toLowerCase());
        if(lowerresult.includes(getdatafromuser)){
          this.viewenabler();
          this.firstbutton = false;
          this.buttondisable = true;
          this.generateotp();
          this.sendautoemail();
          this.startCountdown();
          
          this.Otpresendtimer();
          
          console.log(this.otpdata);

          
        }else{
         window.alert("Fetch error");
        }
 
       }catch(error){
         window.alert("Error Found Catch exception");
       }

      
    }
    //TO SHOW THE OTP FIELD
    viewenabler(){
      this.showotpfield = true;
      this.hideemailfield = true;
      return;
    }


    generateotp() {
        // const randomnumber = Math.random()*9999;
        const formatedotp = Math.floor(Math.random() * (9999 - 1000 + 1)) + 1000
        this.otpdata = formatedotp;
        console.log(this.otpdata);
        return;


  //     fetch('https://randommer.io/api/Number/Generate?Min=1000&Max=9999&Quantity=1', {
  //         method: 'GET',
  //         headers: {
  //             'Accept': 'application/json', // Specify the response format
  //             'X-Api-Key': '', // Correct header key for API key
  //         }
  //     })
  //     .then(response => {
  //         if (!response.ok) {ö
  //             throw new Error('Network response was not ok: ' + response.statusText);
  //         }
  //         return response.json();
  //     })
  //     .then(data => {
  //         this.otpdata = data[0]; // Assuming the API returns an array
  //         console.log('OTP is: ' + this.otpdata);
  //     })
  //     .catch(error => {
  //         console.error('Error fetching OTP:', error);
  //     });
  // }

}


otpvalidate(){
  if(! this.userenteredotp){
    window.alert("Please enter your OTP");
    return;
  }
    if(parseInt(this.userenteredotp) === this.otpdata ){
        
        this.secondbuttonlabel = "Submitted";
        clearInterval(interval);
        this.countdownDisplay = '';
        this.navigatetohome();

    }else{
      window.alert("Invalid OTP");
    }

}

submitdata(){
  this.otpvalidate();
}
resendotp(){
    this.startCountdown();
    this.secondbuttonlabel = "submit";
    this.generateotp();
    this.sendautoemail();
    this.Otpresendtimer();
}


Otpresendtimer(){

  this.resendotpbtnvisibility = true;
  this.timeminutes = Date.now() + 240000;
  clearTimeout(this.timer);
   setTimeout((minu) => {
      this.resendotpbtnvisibility = false;
    }, 240000);
  }

  // getTimeLeft() {
  //   const timeLeft = Math.max(0, this.endTime - Date.now()); 
  //   const minutes = Math.floor(timeLeft / 60000);
  //   const seconds = Math.floor((timeLeft % 60000) / 1000);
  //   return`${minutes}m ${seconds}s`;
  // }


  sendautoemail(){
    sendingemail({toAddress: this.email, otp:this.otpdata});
    return;
  }



  //Function to show timeleft

  

startCountdown() {
    let timeLeft = 4 * 60; // 4 minutes in seconds

    const interval = setInterval(() => {
        let minutes = Math.floor(timeLeft / 60);
        let seconds = timeLeft % 60;
        
        this.countdownDisplay = `Resend OTP by: ${minutes}:${seconds.toString().padStart(2, '0')}`; // Store in variable
        
        if (timeLeft === 0) {
            clearInterval(interval);
            this.countdownDisplay = '';
        } else {
            timeLeft--;
        }
    }, 1000);
}



}











